[2024-01-31T10:03:57.008+0000] {processor.py:161} INFO - Started process (PID=90) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:03:57.009+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:03:57.012+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:03:57.011+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:03:57.022+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:03:57.021+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:03:57.023+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:03:57.042+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.037 seconds
[2024-01-31T10:04:27.550+0000] {processor.py:161} INFO - Started process (PID=148) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:04:27.550+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:04:27.552+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:04:27.551+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:04:27.555+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:04:27.555+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:04:27.556+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:04:27.565+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.018 seconds
[2024-01-31T10:04:58.527+0000] {processor.py:161} INFO - Started process (PID=206) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:04:58.528+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:04:58.529+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:04:58.529+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:04:58.532+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:04:58.532+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:04:58.533+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:04:58.541+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.016 seconds
[2024-01-31T10:05:29.293+0000] {processor.py:161} INFO - Started process (PID=264) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:05:29.294+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:05:29.295+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:05:29.295+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:05:29.298+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:05:29.298+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:05:29.299+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:05:29.307+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.016 seconds
[2024-01-31T10:05:59.979+0000] {processor.py:161} INFO - Started process (PID=322) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:05:59.979+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:05:59.981+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:05:59.980+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:05:59.984+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:05:59.984+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:05:59.984+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:05:59.993+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.016 seconds
[2024-01-31T10:06:30.906+0000] {processor.py:161} INFO - Started process (PID=380) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:06:30.907+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:06:30.908+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:06:30.908+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:06:30.912+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:06:30.911+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:06:30.912+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:06:30.920+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.016 seconds
[2024-01-31T10:07:01.680+0000] {processor.py:161} INFO - Started process (PID=438) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:07:01.681+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:07:01.683+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:07:01.682+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:07:01.687+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:07:01.686+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:07:01.687+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:07:01.697+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.019 seconds
[2024-01-31T10:07:32.352+0000] {processor.py:161} INFO - Started process (PID=496) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:07:32.353+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:07:32.354+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:07:32.354+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:07:32.358+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:07:32.357+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:07:32.358+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:07:32.373+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.023 seconds
[2024-01-31T10:08:03.110+0000] {processor.py:161} INFO - Started process (PID=554) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:08:03.111+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:08:03.112+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:08:03.112+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:08:03.116+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:08:03.115+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:08:03.116+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:08:03.125+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.016 seconds
[2024-01-31T10:08:33.893+0000] {processor.py:161} INFO - Started process (PID=612) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:08:33.894+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:08:33.895+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:08:33.895+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:08:33.899+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:08:33.899+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:08:33.899+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:08:33.909+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.019 seconds
[2024-01-31T10:09:03.969+0000] {processor.py:161} INFO - Started process (PID=670) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:09:03.971+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:09:03.972+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:09:03.972+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:09:03.976+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:09:03.975+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:09:03.976+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:09:03.989+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.022 seconds
[2024-01-31T10:09:34.140+0000] {processor.py:161} INFO - Started process (PID=727) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:09:34.141+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:09:34.142+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:09:34.142+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:09:34.147+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:09:34.146+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:09:34.147+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:09:34.161+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.023 seconds
[2024-01-31T10:10:04.939+0000] {processor.py:161} INFO - Started process (PID=785) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:10:04.940+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:10:04.942+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:10:04.942+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:10:04.947+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:10:04.946+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:10:04.947+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:10:04.961+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.026 seconds
[2024-01-31T10:10:35.351+0000] {processor.py:161} INFO - Started process (PID=843) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:10:35.352+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:10:35.353+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:10:35.353+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:10:35.356+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:10:35.355+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:10:35.356+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:10:35.364+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.015 seconds
[2024-01-31T10:11:05.904+0000] {processor.py:161} INFO - Started process (PID=902) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:11:05.905+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:11:05.906+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:11:05.906+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:11:05.909+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:11:05.909+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:11:05.910+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:11:05.917+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.015 seconds
[2024-01-31T10:11:36.419+0000] {processor.py:161} INFO - Started process (PID=960) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:11:36.420+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:11:36.421+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:11:36.421+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:11:36.424+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:11:36.424+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:11:36.424+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:11:36.434+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.016 seconds
[2024-01-31T10:12:06.682+0000] {processor.py:161} INFO - Started process (PID=1018) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:12:06.682+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:12:06.683+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:12:06.683+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:12:06.686+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:12:06.686+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:12:06.687+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:12:06.694+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.015 seconds
[2024-01-31T10:12:37.397+0000] {processor.py:161} INFO - Started process (PID=1076) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:12:37.398+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:12:37.399+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:12:37.399+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:12:37.402+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:12:37.401+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:12:37.402+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:12:37.410+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.015 seconds
[2024-01-31T10:13:08.084+0000] {processor.py:161} INFO - Started process (PID=1134) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:13:08.085+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:13:08.086+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:13:08.086+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:13:08.089+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:13:08.089+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:13:08.089+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:13:08.097+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.015 seconds
[2024-01-31T10:13:38.993+0000] {processor.py:161} INFO - Started process (PID=1192) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:13:38.994+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:13:38.995+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:13:38.995+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:13:38.998+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:13:38.997+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:13:38.998+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:13:39.007+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.016 seconds
[2024-01-31T10:14:10.151+0000] {processor.py:161} INFO - Started process (PID=1254) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:14:10.153+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:14:10.155+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:14:10.155+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:14:10.160+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:14:10.159+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:14:10.160+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:14:10.177+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.029 seconds
[2024-01-31T10:14:40.972+0000] {processor.py:161} INFO - Started process (PID=1317) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:14:40.973+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:14:40.974+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:14:40.974+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:14:40.978+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:14:40.977+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:14:40.978+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:14:40.987+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.016 seconds
[2024-01-31T10:15:11.791+0000] {processor.py:161} INFO - Started process (PID=1375) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:15:11.791+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:15:11.792+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:15:11.792+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:15:11.796+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:15:11.795+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:15:11.796+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:15:11.804+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.016 seconds
[2024-01-31T10:15:42.604+0000] {processor.py:161} INFO - Started process (PID=1433) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:15:42.605+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:15:42.606+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:15:42.606+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:15:42.609+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:15:42.609+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:15:42.610+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:15:42.617+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.015 seconds
[2024-01-31T10:16:13.393+0000] {processor.py:161} INFO - Started process (PID=1491) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:16:13.394+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:16:13.395+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:16:13.395+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:16:13.399+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:16:13.398+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:16:13.399+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:16:13.408+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.017 seconds
[2024-01-31T10:16:44.302+0000] {processor.py:161} INFO - Started process (PID=1549) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:16:44.303+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:16:44.304+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:16:44.304+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:16:44.307+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:16:44.307+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:16:44.307+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:16:44.316+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.015 seconds
[2024-01-31T10:17:15.193+0000] {processor.py:161} INFO - Started process (PID=1607) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:17:15.194+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:17:15.195+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:17:15.195+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:17:15.198+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:17:15.198+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:17:15.198+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:17:15.207+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.016 seconds
[2024-01-31T10:17:46.072+0000] {processor.py:161} INFO - Started process (PID=1665) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:17:46.073+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:17:46.075+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:17:46.074+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:17:46.084+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:17:46.082+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:17:46.086+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:17:46.103+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.034 seconds
[2024-01-31T10:18:17.287+0000] {processor.py:161} INFO - Started process (PID=1723) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:18:17.288+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:18:17.290+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:18:17.290+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:18:17.309+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:18:17.305+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:18:17.310+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:18:17.343+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.058 seconds
[2024-01-31T10:18:47.410+0000] {processor.py:161} INFO - Started process (PID=1781) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:18:47.411+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:18:47.412+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:18:47.412+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:18:47.416+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:18:47.415+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:18:47.416+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:18:47.425+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.017 seconds
[2024-01-31T10:19:17.800+0000] {processor.py:161} INFO - Started process (PID=1846) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:19:17.801+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:19:17.803+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:19:17.802+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:19:17.806+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:19:17.805+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:19:17.806+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:19:17.815+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.017 seconds
[2024-01-31T10:19:47.957+0000] {processor.py:161} INFO - Started process (PID=1907) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:19:47.958+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:19:47.959+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:19:47.959+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:19:47.963+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:19:47.963+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:19:47.964+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:19:47.974+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.019 seconds
[2024-01-31T10:20:19.089+0000] {processor.py:161} INFO - Started process (PID=1974) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:20:19.090+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:20:19.091+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:20:19.091+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:20:19.095+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:20:19.094+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:20:19.095+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:20:19.103+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.015 seconds
[2024-01-31T10:20:49.303+0000] {processor.py:161} INFO - Started process (PID=2035) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:20:49.304+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:20:49.305+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:20:49.305+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:20:49.308+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:20:49.308+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:20:49.309+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:20:49.317+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.015 seconds
[2024-01-31T10:21:20.191+0000] {processor.py:161} INFO - Started process (PID=2096) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:21:20.192+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:21:20.193+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:21:20.193+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:21:20.196+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:21:20.196+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:21:20.196+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:21:20.206+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.018 seconds
[2024-01-31T10:21:51.135+0000] {processor.py:161} INFO - Started process (PID=2157) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:21:51.136+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:21:51.137+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:21:51.137+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:21:51.140+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:21:51.140+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:21:51.140+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:21:51.149+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.016 seconds
[2024-01-31T10:22:22.220+0000] {processor.py:161} INFO - Started process (PID=2217) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:22:22.221+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:22:22.222+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:22:22.222+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:22:22.225+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:22:22.225+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:22:22.226+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:22:22.234+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.016 seconds
[2024-01-31T10:22:56.414+0000] {processor.py:161} INFO - Started process (PID=2292) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:22:56.417+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:22:56.420+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:22:56.419+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:22:56.458+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:22:56.445+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:22:56.461+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:22:56.523+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.113 seconds
[2024-01-31T10:23:27.435+0000] {processor.py:161} INFO - Started process (PID=2359) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:23:27.436+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:23:27.437+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:23:27.437+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:23:27.442+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:23:27.440+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:23:27.442+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:23:27.451+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.018 seconds
[2024-01-31T10:23:57.736+0000] {processor.py:161} INFO - Started process (PID=2420) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:23:57.738+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:23:57.739+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:23:57.739+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:23:57.743+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:23:57.742+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:23:57.743+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:23:57.753+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.019 seconds
[2024-01-31T10:24:28.101+0000] {processor.py:161} INFO - Started process (PID=2481) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:24:28.102+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:24:28.103+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:24:28.103+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:24:28.107+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:24:28.107+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:24:28.107+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:24:28.117+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.018 seconds
[2024-01-31T10:24:58.215+0000] {processor.py:161} INFO - Started process (PID=2542) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:24:58.216+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:24:58.218+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:24:58.217+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:24:58.221+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:24:58.220+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:24:58.221+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:24:58.232+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.019 seconds
[2024-01-31T10:25:29.186+0000] {processor.py:161} INFO - Started process (PID=2603) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:25:29.187+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:25:29.188+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:25:29.188+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:25:29.191+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:25:29.191+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:25:29.191+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:25:29.200+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.016 seconds
[2024-01-31T10:25:59.388+0000] {processor.py:161} INFO - Started process (PID=2664) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:25:59.389+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:25:59.390+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:25:59.390+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:25:59.394+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:25:59.393+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:25:59.394+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:25:59.402+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.016 seconds
[2024-01-31T10:26:29.517+0000] {processor.py:161} INFO - Started process (PID=2725) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:26:29.518+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:26:29.519+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:26:29.519+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:26:29.522+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:26:29.522+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:26:29.522+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:26:29.531+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.015 seconds
[2024-01-31T10:26:59.674+0000] {processor.py:161} INFO - Started process (PID=2786) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:26:59.675+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:26:59.677+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:26:59.676+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:26:59.680+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:26:59.680+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:26:59.681+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:26:59.692+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.021 seconds
[2024-01-31T10:27:29.951+0000] {processor.py:161} INFO - Started process (PID=2847) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:27:29.952+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:27:29.953+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:27:29.953+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:27:29.957+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:27:29.956+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:27:29.957+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:27:29.966+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.018 seconds
[2024-01-31T10:28:00.497+0000] {processor.py:161} INFO - Started process (PID=2908) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:28:00.498+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:28:00.500+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:28:00.499+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:28:00.504+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:28:00.503+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:28:00.504+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:28:00.513+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.018 seconds
[2024-01-31T10:28:30.854+0000] {processor.py:161} INFO - Started process (PID=2976) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:28:30.854+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:28:30.855+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:28:30.855+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:28:30.860+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:28:30.859+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:28:30.860+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:28:30.869+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.017 seconds
[2024-01-31T10:29:01.600+0000] {processor.py:161} INFO - Started process (PID=3037) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:29:01.601+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:29:01.602+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:29:01.602+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:29:01.606+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:29:01.606+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:29:01.606+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:29:01.616+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.019 seconds
[2024-01-31T10:29:31.961+0000] {processor.py:161} INFO - Started process (PID=3098) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:29:31.962+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:29:31.963+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:29:31.963+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:29:31.967+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:29:31.966+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:29:31.967+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:29:31.975+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.016 seconds
[2024-01-31T10:30:02.703+0000] {processor.py:161} INFO - Started process (PID=3159) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:30:02.704+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:30:02.705+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:30:02.705+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:30:02.709+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:30:02.708+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:30:02.709+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:30:02.717+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.016 seconds
[2024-01-31T10:30:32.804+0000] {processor.py:161} INFO - Started process (PID=3220) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:30:32.805+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:30:32.806+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:30:32.806+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:30:32.810+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:30:32.809+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:30:32.810+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:30:32.817+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.015 seconds
[2024-01-31T10:31:02.917+0000] {processor.py:161} INFO - Started process (PID=3281) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:31:02.918+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:31:02.919+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:31:02.919+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:31:02.925+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:31:02.924+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:31:02.925+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:31:02.932+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.017 seconds
[2024-01-31T10:31:33.055+0000] {processor.py:161} INFO - Started process (PID=3342) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:31:33.056+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:31:33.057+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:31:33.056+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:31:33.060+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:31:33.060+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:31:33.061+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:31:33.069+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.017 seconds
[2024-01-31T10:32:03.238+0000] {processor.py:161} INFO - Started process (PID=3403) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:32:03.239+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:32:03.241+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:32:03.241+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:32:03.244+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:32:03.244+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:32:03.245+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:32:03.254+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.018 seconds
[2024-01-31T10:32:33.368+0000] {processor.py:161} INFO - Started process (PID=3464) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:32:33.369+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:32:33.371+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:32:33.371+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:32:33.375+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:32:33.374+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:32:33.375+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:32:33.383+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.017 seconds
[2024-01-31T10:33:03.941+0000] {processor.py:161} INFO - Started process (PID=3525) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:33:03.942+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:33:03.943+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:33:03.943+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:33:03.947+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:33:03.947+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:33:03.948+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:33:03.960+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.021 seconds
[2024-01-31T10:33:34.159+0000] {processor.py:161} INFO - Started process (PID=3586) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:33:34.160+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:33:34.161+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:33:34.161+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:33:34.164+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:33:34.164+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:33:34.165+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:33:34.173+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.016 seconds
[2024-01-31T10:34:04.717+0000] {processor.py:161} INFO - Started process (PID=3647) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:34:04.719+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:34:04.721+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:34:04.721+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:34:04.727+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:34:04.726+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:34:04.727+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:34:04.735+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.020 seconds
[2024-01-31T10:34:34.950+0000] {processor.py:161} INFO - Started process (PID=3708) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:34:34.951+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:34:34.952+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:34:34.952+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:34:34.955+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:34:34.955+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:34:34.956+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:34:34.963+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.015 seconds
[2024-01-31T10:35:05.202+0000] {processor.py:161} INFO - Started process (PID=3769) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:35:05.203+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:35:05.204+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:35:05.204+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:35:05.208+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:35:05.207+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:35:05.208+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:35:05.216+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.017 seconds
[2024-01-31T10:35:35.799+0000] {processor.py:161} INFO - Started process (PID=3830) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:35:35.800+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:35:35.801+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:35:35.801+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:35:35.805+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:35:35.804+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:35:35.805+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:35:35.818+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.021 seconds
[2024-01-31T10:36:06.237+0000] {processor.py:161} INFO - Started process (PID=3891) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:36:06.238+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:36:06.239+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:36:06.239+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:36:06.242+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:36:06.241+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:36:06.242+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:36:06.251+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.016 seconds
[2024-01-31T10:36:36.570+0000] {processor.py:161} INFO - Started process (PID=3952) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:36:36.571+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:36:36.572+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:36:36.572+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:36:36.576+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:36:36.575+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:36:36.576+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:36:36.584+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.016 seconds
[2024-01-31T10:37:06.814+0000] {processor.py:161} INFO - Started process (PID=4013) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:37:06.816+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:37:06.817+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:37:06.817+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:37:06.820+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:37:06.820+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:37:06.820+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:37:06.829+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.017 seconds
[2024-01-31T10:37:37.157+0000] {processor.py:161} INFO - Started process (PID=4074) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:37:37.158+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:37:37.160+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:37:37.160+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:37:37.163+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:37:37.163+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:37:37.163+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:37:37.172+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.017 seconds
[2024-01-31T10:38:07.612+0000] {processor.py:161} INFO - Started process (PID=4135) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:38:07.613+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:38:07.614+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:38:07.614+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:38:07.618+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:38:07.618+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:38:07.618+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:38:07.629+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.019 seconds
[2024-01-31T10:38:37.689+0000] {processor.py:161} INFO - Started process (PID=4196) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:38:37.690+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:38:37.691+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:38:37.691+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:38:37.695+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:38:37.694+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:38:37.695+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:38:37.703+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.016 seconds
[2024-01-31T10:39:08.048+0000] {processor.py:161} INFO - Started process (PID=4257) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:39:08.049+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:39:08.051+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:39:08.050+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:39:08.054+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:39:08.053+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:39:08.054+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:39:08.062+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.015 seconds
[2024-01-31T10:39:39.117+0000] {processor.py:161} INFO - Started process (PID=4318) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:39:39.119+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:39:39.120+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:39:39.120+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:39:39.124+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:39:39.123+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:39:39.124+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:39:39.133+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.018 seconds
[2024-01-31T10:40:10.183+0000] {processor.py:161} INFO - Started process (PID=4379) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:40:10.185+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:40:10.186+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:40:10.186+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:40:10.189+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:40:10.189+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:40:10.189+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:40:10.198+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.016 seconds
[2024-01-31T10:40:41.220+0000] {processor.py:161} INFO - Started process (PID=4440) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:40:41.222+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:40:41.223+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:40:41.223+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:40:41.226+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:40:41.226+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:40:41.227+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:40:41.235+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.016 seconds
[2024-01-31T10:41:11.400+0000] {processor.py:161} INFO - Started process (PID=4501) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:41:11.401+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:41:11.402+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:41:11.402+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:41:11.409+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:41:11.408+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:41:11.409+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:41:11.422+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.024 seconds
[2024-01-31T10:41:41.603+0000] {processor.py:161} INFO - Started process (PID=4562) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:41:41.605+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:41:41.606+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:41:41.606+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:41:41.612+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:41:41.611+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:41:41.612+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:41:41.624+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.023 seconds
[2024-01-31T10:42:11.708+0000] {processor.py:161} INFO - Started process (PID=4623) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:42:11.709+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:42:11.710+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:42:11.710+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:42:11.714+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:42:11.713+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:42:11.714+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:42:11.722+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.016 seconds
[2024-01-31T10:42:42.555+0000] {processor.py:161} INFO - Started process (PID=4684) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:42:42.557+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:42:42.558+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:42:42.558+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:42:42.562+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:42:42.561+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:42:42.562+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:42:42.571+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.017 seconds
[2024-01-31T10:43:12.740+0000] {processor.py:161} INFO - Started process (PID=4745) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:43:12.741+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:43:12.742+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:43:12.742+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:43:12.746+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:43:12.745+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:43:12.746+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:43:12.755+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.017 seconds
[2024-01-31T10:43:42.888+0000] {processor.py:161} INFO - Started process (PID=4806) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:43:42.889+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:43:42.890+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:43:42.890+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:43:42.894+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:43:42.893+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:43:42.894+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:43:42.912+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.026 seconds
[2024-01-31T10:44:13.655+0000] {processor.py:161} INFO - Started process (PID=4867) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:44:13.656+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:44:13.658+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:44:13.657+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:44:13.663+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:44:13.663+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:44:13.664+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:44:13.672+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.019 seconds
[2024-01-31T10:44:43.787+0000] {processor.py:161} INFO - Started process (PID=4928) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:44:43.788+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:44:43.790+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:44:43.789+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:44:43.793+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:44:43.793+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:44:43.793+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:44:43.802+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.016 seconds
[2024-01-31T10:45:14.785+0000] {processor.py:161} INFO - Started process (PID=4989) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:45:14.786+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:45:14.787+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:45:14.787+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:45:14.790+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:45:14.790+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:45:14.791+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:45:14.799+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.016 seconds
[2024-01-31T10:45:44.911+0000] {processor.py:161} INFO - Started process (PID=5050) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:45:44.912+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:45:44.913+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:45:44.913+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:45:44.917+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:45:44.916+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:45:44.917+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:45:44.925+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.016 seconds
[2024-01-31T10:46:15.968+0000] {processor.py:161} INFO - Started process (PID=5111) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:46:15.969+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:46:15.971+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:46:15.970+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:46:15.975+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:46:15.974+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:46:15.975+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:46:15.984+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.017 seconds
[2024-01-31T10:46:46.181+0000] {processor.py:161} INFO - Started process (PID=5172) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:46:46.182+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:46:46.183+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:46:46.183+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:46:46.187+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:46:46.187+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:46:46.188+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:46:46.196+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.017 seconds
[2024-01-31T10:47:17.199+0000] {processor.py:161} INFO - Started process (PID=5233) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:47:17.201+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:47:17.202+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:47:17.202+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:47:17.206+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:47:17.205+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:47:17.206+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:47:17.214+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.017 seconds
[2024-01-31T10:47:48.257+0000] {processor.py:161} INFO - Started process (PID=5294) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:47:48.259+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:47:48.261+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:47:48.260+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:47:48.264+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:47:48.263+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:47:48.264+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:47:48.273+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.018 seconds
[2024-01-31T10:48:19.282+0000] {processor.py:161} INFO - Started process (PID=5355) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:48:19.283+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:48:19.284+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:48:19.284+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:48:19.287+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:48:19.287+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:48:19.288+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:48:19.297+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.017 seconds
[2024-01-31T10:48:49.594+0000] {processor.py:161} INFO - Started process (PID=5416) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:48:49.595+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:48:49.598+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:48:49.597+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:48:49.602+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:48:49.601+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:48:49.602+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:48:49.612+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.021 seconds
[2024-01-31T10:49:20.044+0000] {processor.py:161} INFO - Started process (PID=5477) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:49:20.045+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:49:20.047+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:49:20.047+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:49:20.053+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:49:20.052+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:49:20.053+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:49:20.063+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.020 seconds
[2024-01-31T10:49:50.140+0000] {processor.py:161} INFO - Started process (PID=5538) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:49:50.141+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:49:50.142+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:49:50.141+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:49:50.147+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:49:50.146+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:49:50.147+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:49:50.156+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.018 seconds
[2024-01-31T10:50:21.080+0000] {processor.py:161} INFO - Started process (PID=5599) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:50:21.081+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:50:21.082+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:50:21.082+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:50:21.086+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:50:21.085+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:50:21.086+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:50:21.095+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.017 seconds
[2024-01-31T10:50:52.165+0000] {processor.py:161} INFO - Started process (PID=5660) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:50:52.167+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:50:52.168+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:50:52.168+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:50:52.172+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:50:52.172+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:50:52.173+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:50:52.182+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.020 seconds
[2024-01-31T10:51:23.150+0000] {processor.py:161} INFO - Started process (PID=5721) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:51:23.151+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:51:23.152+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:51:23.152+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:51:23.155+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:51:23.155+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:51:23.155+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:51:23.164+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.016 seconds
[2024-01-31T10:51:54.184+0000] {processor.py:161} INFO - Started process (PID=5782) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:51:54.186+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:51:54.187+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:51:54.187+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:51:54.190+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:51:54.190+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:51:54.191+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:51:54.199+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.017 seconds
[2024-01-31T10:52:24.513+0000] {processor.py:161} INFO - Started process (PID=5843) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:52:24.515+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:52:24.516+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:52:24.516+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:52:24.521+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:52:24.521+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:52:24.522+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:52:24.531+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.020 seconds
[2024-01-31T10:52:54.626+0000] {processor.py:161} INFO - Started process (PID=5904) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:52:54.628+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:52:54.629+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:52:54.629+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:52:54.633+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:52:54.632+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:52:54.633+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:52:54.641+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.016 seconds
[2024-01-31T10:53:25.764+0000] {processor.py:161} INFO - Started process (PID=5965) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:53:25.767+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:53:25.768+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:53:25.768+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:53:25.773+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:53:25.772+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:53:25.773+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:53:25.783+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.022 seconds
[2024-01-31T10:53:56.140+0000] {processor.py:161} INFO - Started process (PID=6026) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:53:56.142+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:53:56.144+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:53:56.144+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:53:56.149+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:53:56.148+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:53:56.149+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:53:56.158+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.020 seconds
[2024-01-31T10:54:26.461+0000] {processor.py:161} INFO - Started process (PID=6087) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:54:26.462+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:54:26.463+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:54:26.463+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:54:26.467+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:54:26.466+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:54:26.467+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:54:26.475+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.016 seconds
[2024-01-31T10:54:56.759+0000] {processor.py:161} INFO - Started process (PID=6154) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:54:56.760+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:54:56.761+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:54:56.761+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:54:56.764+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:54:56.764+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:54:56.765+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:54:56.773+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.016 seconds
[2024-01-31T10:55:28.308+0000] {processor.py:161} INFO - Started process (PID=6215) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:55:28.309+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:55:28.310+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:55:28.310+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:55:28.314+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:55:28.313+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:55:28.314+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:55:28.324+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.018 seconds
[2024-01-31T10:55:58.941+0000] {processor.py:161} INFO - Started process (PID=6276) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:55:58.943+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:55:58.945+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:55:58.944+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:55:58.948+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:55:58.947+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:55:58.948+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:55:58.956+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.018 seconds
[2024-01-31T10:56:29.239+0000] {processor.py:161} INFO - Started process (PID=6337) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:56:29.240+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:56:29.241+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:56:29.241+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:56:29.245+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:56:29.244+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:56:29.245+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:56:29.253+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.017 seconds
[2024-01-31T10:56:59.858+0000] {processor.py:161} INFO - Started process (PID=6398) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:56:59.860+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:56:59.861+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:56:59.861+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:56:59.866+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:56:59.866+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:56:59.867+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:56:59.880+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.024 seconds
[2024-01-31T10:57:29.974+0000] {processor.py:161} INFO - Started process (PID=6459) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:57:29.974+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:57:29.976+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:57:29.975+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:57:29.978+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:57:29.978+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:57:29.979+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:57:29.986+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.015 seconds
[2024-01-31T10:58:01.103+0000] {processor.py:161} INFO - Started process (PID=6520) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:58:01.104+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:58:01.105+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:58:01.105+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:58:01.110+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:58:01.109+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:58:01.110+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:58:01.118+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.017 seconds
[2024-01-31T10:58:31.913+0000] {processor.py:161} INFO - Started process (PID=6581) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:58:31.915+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:58:31.916+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:58:31.916+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:58:31.920+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:58:31.919+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:58:31.920+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:58:31.928+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.017 seconds
[2024-01-31T10:59:05.930+0000] {processor.py:161} INFO - Started process (PID=6642) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:59:05.932+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:59:05.934+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:59:05.934+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:59:05.938+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:59:05.937+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:59:05.938+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:59:05.947+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.019 seconds
[2024-01-31T10:59:36.159+0000] {processor.py:161} INFO - Started process (PID=6703) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:59:36.160+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T10:59:36.162+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:59:36.162+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:59:36.165+0000] {logging_mixin.py:188} INFO - [2024-01-31T10:59:36.165+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T10:59:36.166+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T10:59:36.174+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.018 seconds
[2024-01-31T11:00:07.361+0000] {processor.py:161} INFO - Started process (PID=6764) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T11:00:07.364+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T11:00:07.367+0000] {logging_mixin.py:188} INFO - [2024-01-31T11:00:07.367+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T11:00:07.374+0000] {logging_mixin.py:188} INFO - [2024-01-31T11:00:07.373+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T11:00:07.375+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T11:00:07.400+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.043 seconds
[2024-01-31T11:00:37.743+0000] {processor.py:161} INFO - Started process (PID=6825) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T11:00:37.744+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T11:00:37.747+0000] {logging_mixin.py:188} INFO - [2024-01-31T11:00:37.746+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T11:00:37.752+0000] {logging_mixin.py:188} INFO - [2024-01-31T11:00:37.751+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T11:00:37.752+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T11:00:37.775+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.035 seconds
[2024-01-31T11:01:08.646+0000] {processor.py:161} INFO - Started process (PID=6886) to work on /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T11:01:08.648+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/great_expectations_bigquery.py for tasks to queue
[2024-01-31T11:01:08.649+0000] {logging_mixin.py:188} INFO - [2024-01-31T11:01:08.649+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T11:01:08.652+0000] {logging_mixin.py:188} INFO - [2024-01-31T11:01:08.652+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/great_expectations_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/great_expectations_bigquery.py", line 34, in <module>
    from great_expectations_provider.operators.great_expectations import (
ModuleNotFoundError: No module named 'great_expectations_provider'
[2024-01-31T11:01:08.652+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/great_expectations_bigquery.py
[2024-01-31T11:01:08.661+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/great_expectations_bigquery.py took 0.017 seconds
